### ISSUE TITLE
Each place of moztw-lab should be linkable.

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#10]
http://moztw/events/moztw-lab/

Current it only default to showing information of Taipei, 
The url for each places should be linkable, for ex.,
http://moztw/events/moztw-lab/#hc for HsinChu, 
http://moztw/events/moztw-lab/#kl for Keelung,

and based on the hash tag to default showing information of different location.

**Comment by wi1d5ky** [comment]
網址支援 http://moztw.org/events/moztw-lab/
