### ISSUE TITLE
首頁切換 Sandstone

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#107]
目前開發進度：http://moztw.org/index2.html
主要要修復中間的下載按鈕（目前是 404），接著把下方內容補完，即可切換

**Comment by wi1d5ky** [comment]
剛發現一個問題，小莎在說話的時候如果抓的字太多就會 <del>overflow</del> 滿到下面去

![2015-03-12 23 25 13](https://cloud.githubusercontent.com/assets/6042803/6621040/36236b18-c90f-11e4-83b4-d26e39275acf.png)
![2015-03-12 23 27 26](https://cloud.githubusercontent.com/assets/6042803/6621078/5ffc34a6-c90f-11e4-9ffb-77fe36853c91.png)

**Comment by irvin** [comment]
直接讓他可以變成多行吧，反正手機版也會遇到
wildsky <notifications@github.com>於 2015年3月12日 週四，下午11:28寫道：

**Comment by wildskyf** [comment]
結果現在 feed 全部死光光了XD

**Comment by wildskyf** [comment]
而且 mozilla 把 sandstone 換掉惹

**Comment by irvin** [comment]
暫時也沒有這麼多訊息的需求了，還是關了吧⋯⋯
