### ISSUE TITLE
Foxmosa 加上 Line 貼圖與下載Telegram 貼圖連結

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#121]
Telegram 貼圖連結： https://www.dropbox.com/s/h8cmf2f6iu3vpm3/Foxmosa%20IM%20Stickers%20%28cc-by-nc-sa-3.0%20%40MozTW%20x%20P.C.polliwog%29.zip?dl=0
Line 貼圖連結： https://store.line.me/stickershop/product/1005599/

**Comment by irvin** [comment]
Telegram 貼圖連結： https://www.dropbox.com/s/h8cmf2f6iu3vpm3/Foxmosa%20IM%20Stickers%20%28cc-by-nc-sa-3.0%20%40MozTW%20x%20P.C.polliwog%29.zip?dl=0
Line 貼圖連結： https://store.line.me/stickershop/product/1005599/

**Comment by petercpg** [comment]
貼圖丟到 MozTW 主機比較好吧？Dropbox 容易一陣子死連結。

**Comment by irvin** [comment]
只是先暫時丟那邊

**Comment by wi1d5ky** [comment]
https://www.dropbox.com/s/h8cmf2f6iu3vpm3/Foxmosa%20IM%20Stickers%20%28cc-by-nc-sa-3.0%20%40MozTW%20x%20P.C.polliwog%29.zip?dl=0
後面的 dl=0 改成 dl=1 就可以直接下載
變成這樣:
https://www.dropbox.com/s/h8cmf2f6iu3vpm3/Foxmosa%20IM%20Stickers%20%28cc-by-nc-sa-3.0%20%40MozTW%20x%20P.C.polliwog%29.zip?dl=1
剛好想到就提一下 XD

**Comment by wi1d5ky** [comment]
https://github.com/moztw/www.moztw.org/pull/129  (遞

**Comment by irvin** [comment]
Merge 了，下次最好把 PR 分開，一個 merge 只做一件事情的原則

**Comment by wi1d5ky** [comment]
好，不過我不太清楚要怎麼開第二個PR，當時要送的時候發現只有 view pull request 的選項而已…@@
是要開一個新的 ｂｒａｃｈ 去做第二件事嗎？

**Comment by irvin** [comment]
對，理論上我們應該要把 feature 分 branch 來做，不過同時間沒有這麼多修改的時候，先不管好了

**Comment by wi1d5ky** [comment]
OK，下次會注意！
還要說聲抱歉，因為我還不熟悉 git 的使用，所以會有很多問題，我會努力的 >___<

**Comment by irvin** [comment]
你也可以研究一下 git rebase -i，就可以把 commit 都整理好再發 PR 了，會漂亮很多

**Comment by wi1d5ky** [comment]
我好像有用過 rebase，不過當時是為了與被 fork 的 repo 同步才用
好像是可以避免冗餘的 merge commit，我再去研究研究

**Comment by irvin** [comment]
rebase 我常用的有兩種功能，
一種是把已經修改很久的 branch，把上游的修改併進來，把 branch 分叉的地方往後哪。
另一種 rebase -i 是可以把每個 commit 都重新來一遍，途中可以合併或修改任何變動。

於 2015年1月19日 於 下午4:00:10, wildsky (notifications@github.com) 寫:

我好像有用過 rebase，不過當時是為了與被 fork 的 repo 同步才用
好像是可以避免冗餘的 merge commit，我再去研究研究

**Comment by appleboy** [comment]
我超常用第一種 git rebase. 把舊的 branch commit 拉到最上面
