### ISSUE TITLE
把台灣版網頁的「套件安裝」與「下載」連結指向本地的檔案

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#132]
myfirefox 關門了，因此那些套件與安裝黨不知會在何時被取下。
最為數位典藏，套件安裝與下載按鈕需要指回自己本機上的備份檔案。

**Comment by irvin** [comment]
https://drive.google.com/open?id=0B9BU22m9p7kqanhSV2kzMTVQY3M&authuser=0 安裝檔與套件 xpi 備份

**Comment by petercpg** [comment]
我想應該比照 mozilla suite 的 notice 處理就可以了，我們不必特別 host 這些檔案。如果有其他需要可以 fork addon
的 github repo 過來留著。

另外 MoCo 的「使用者體驗改善計畫」
http://mozilla.com.tw/firefox/ueip/ 也會重導去其他地方。
2015/1/19 下午2:28 於 "Irvin" <notifications@github.com> 寫道：

**Comment by irvin** [comment]
不是每一個 addon 都有 github repo (也只有幾個有上 addon.mozilla.org)
作為典藏的目的，放著還是不錯，以後有人要找也只能來這了

2015-01-19 14:51 GMT+08:00 Peter Chen <notifications@github.com>:

> 我想應該比照 mozilla suite 的 notice 處理就可以了，我們不必特別 host 這些檔案。如果有其他需要可以 fork addon
> 的 github repo 過來留著。
>
> 另外 MoCo 的「使用者體驗改善計畫」
> http://mozilla.com.tw/firefox/ueip/ 也會重導去其他地方。
> 2015/1/19 下午2:28 於 "Irvin" <notifications@github.com> 寫道：
>
> > myfirefox 關門了，因此那些套件也不知道會在何時被取下，安裝按鈕需要指回自己本機上
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/moztw/www.moztw.org/issues/132>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/132#issuecomment-70452619>.
>



-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by irvin** [comment]
人事已非，「使用體驗改善計畫」跟其他被 PR 的內容可以退回最早我們的用詞，不用這麼隱晦了。

2015-01-19 15:02 GMT+08:00 Irvin Chen <irvin@mail.moztw.org>:

> 不是每一個 addon 都有 github repo (也只有幾個有上 addon.mozilla.org)
> 作為典藏的目的，放著還是不錯，以後有人要找也只能來這了
>
> 2015-01-19 14:51 GMT+08:00 Peter Chen <notifications@github.com>:
>
>> 我想應該比照 mozilla suite 的 notice 處理就可以了，我們不必特別 host 這些檔案。如果有其他需要可以 fork
>> addon
>> 的 github repo 過來留著。
>>
>> 另外 MoCo 的「使用者體驗改善計畫」
>> http://mozilla.com.tw/firefox/ueip/ 也會重導去其他地方。
>> 2015/1/19 下午2:28 於 "Irvin" <notifications@github.com> 寫道：
>>
>> > myfirefox 關門了，因此那些套件也不知道會在何時被取下，安裝按鈕需要指回自己本機上
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/moztw/www.moztw.org/issues/132>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/moztw/www.moztw.org/issues/132#issuecomment-70452619>
>> .
>>
>
>
>
> --
> @ irvinfly: community liaison
> moztw.org Mozilla Taiwan community
>



-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by mingtsay** [comment]
那要由我來更新嗎？今天晚上我可以更新這頁！

**Comment by mingtsay** [comment]
@irvin 要連同修改過的 installer 一起備份嗎？

**Comment by mingtsay** [comment]
預覽可直接在 http://issue-132.moztw.demo-mt.tk/firefox/tw/ 觀看，或是 `git checkout issue-132`
- 套件備份在 https://github.com/moztw/www.moztw.org/tree/issue-132/firefox/tw/xpi
- 安裝檔備份在 https://github.com/moztw/www.moztw.org/tree/issue-132/firefox/tw/dl
- 修改了部分的文字敘述（包含還原以前的敘述）

麻煩各位 review 了（commit 8bc7ecdea620806156fb5f228045171b2790a6d6）

**Comment by petercpg** [comment]
binary code 這種呆重就不要丟進 git repo 了吧？比照我們 host Firefox 1.x 安裝檔的方式丟到 var 裡面指過來提供下載就好了？

另外嚴謹一點的話，最好我們還要提供使用者 checksum 看看檔案是不是正確的。

**Comment by petercpg** [comment]
我丟了一份到主機上：
* http://moztw.org/dls/fx/mocotwver/Firefox-full-latest.exe
* http://moztw.org/dls/fx/mocotwver/Firefox-latest.dmg
* http://moztw.org/dls/fx/mocotwver/Firefox-latest.tar.bz2
* http://moztw.org/dls/fx/mocotwver/Firefox-latest-x86_64.tar.bz2
* http://moztw.org/dls/fx/mocotwver/xpi/addon-1.0.1-fx.xpi
* http://moztw.org/dls/fx/mocotwver/xpi/easyscreenshot-0.2.1.1.xpi
* http://moztw.org/dls/fx/mocotwver/xpi/fontsetter-1.0.0.xpi
* http://moztw.org/dls/fx/mocotwver/xpi/fx-improvement-0.2.0.1.xpi
* http://moztw.org/dls/fx/mocotwver/xpi/personas_plus-1.7.3-fx+tb.xpi
* http://moztw.org/dls/fx/mocotwver/xpi/tabimprovelite-2.0.1.xpi
* http://moztw.org/dls/fx/mocotwver/xpi/tpmanager-0.2.1.xpi
* http://moztw.org/dls/fx/mocotwver/xpi/twhomepage-0.2.2.xpi
* http://moztw.org/dls/fx/mocotwver/xpi/zoompanel-2.0.0.xpi

**Comment by mingtsay** [comment]
我晚點把呆重檔案從 repo 移除，然後改成加上 checksum 在 repo 裡面，謝謝 Peter

**Comment by petercpg** [comment]
https://github.com/moztw/www.moztw.org/commit/8bc7ecdea620806156fb5f228045171b2790a6d6 這個 commit 記得拆掉重推，剛剛 git pull 卡了好久...orz

**Comment by mingtsay** [comment]
已用 `git rebase -i HEAD~2` 與 `git push origin +issue132` 把 8bc7ecd 移除了，抱歉造成困擾

**Comment by irvin** [comment]
這個 commit 直接推進 www.moztw.org 的 repo，沒有用 PR 的方式，所以直接已經進到 git tree 沒救了。
只有用某些奇技淫巧把整個 tree 重寫，才能把 commit 過的檔案佔用的空間清除。

我剛剛整理了一下群組跟權限，今後除了更新 Release 等常態事項外，大家都改用發 PR 的方式吧來 patch 吧，至少能在 PR 階段把一些問題在 Repo 之外先擋掉。

**Comment by petercpg** [comment]
有問題的東西只在 issue-132 這個 branch，從 master checkout 一個新的 branch，然後把要的變更移植過來，再把
issue-132 branch 砍掉之後再清掉 reflog 就沒問題了吧？

**Comment by irvin** [comment]
做做看？沒有進 master 我沒處理過，好像跟下面步驟有點出入
https://help.github.com/articles/remove-sensitive-data/



Peter Chen <notifications@github.com> 於 2015年4月9日 下午1:20 寫道：

> 有問題的東西只在 issue-132 這個 branch，從 master checkout 一個新的 branch，然後把要的變更移植過來，再把
> issue-132 branch 砍掉之後再清掉 reflog 就沒問題了吧？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/132#issuecomment-91118262>.
>



-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by mingtsay** [comment]
照理是應該可以先輸出 diff 然後把整個 `issue-132` 摘掉

**Comment by petercpg** [comment]
搞定，後續請在 issue-132-new branch 繼續作業。

**Comment by irvin** [comment]
現在小喵不能直接推 www.moztw.org 了，建議直接重新拉回去個人 repo，改好直接對 master 送 PR 吧

**Comment by petercpg** [comment]
已經 merge 回 master 了，目前看起來沒啥問題。

另外別忘記還有 #131 。

**Comment by irvin** [comment]
thanks
