### ISSUE TITLE
確認 /firefox-new 的下載鈕正常

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#134]
需要確認他已經能判斷 OS 平台，提供正確的下載鈕。

**Comment by irvin** [comment]
@wi1d5ky 可以幫忙確認一下看看嗎？

**Comment by wi1d5ky** [comment]
windows 會跳到 <a href="http://moztw.org/firefox/download/latest-win.html">這裡</a>，正常
Android_zenfone5，下載鈕不見了....(如下圖)
<img src="https://s3.amazonaws.com/pushbullet-uploads/ujEuDWG4uzI-y4uhs5lmfIECugnmVHOpklfEkByM9syL/Screenshot_2015-01-19-15-50-18.png" height="500px" width="auto">

**Comment by irvin** [comment]
那就加上按鈕連到 Play Store 去吧～
https://play.google.com/store/apps/details?id=org.mozilla.firefox

**Comment by wi1d5ky** [comment]
不過還蠻奇怪的，明明電腦上用適應性設計模式看按鈕就還在，在手機上看卻不見了

**Comment by irvin** [comment]
看 js，在無法用 ua 判斷是那顆按鈕時，應該要有一顆通用的按鈕（或只剩下全部平台的連結）出現才對

**Comment by wi1d5ky** [comment]
咦? @irvin osx 上的按鈕是正確的嗎?
download.js 裡面是 mac, 可是 diff-new.html 是 osx ?

**Comment by wi1d5ky** [comment]
Btw，我增加 android 的按鈕後，要順便調他的位置再一起送 PR 嗎？ (issue https://github.com/moztw/www.moztw.org/issues/94 下面提到的"下方壓字問題")

**Comment by irvin** [comment]
sure

2015-01-19 18:31 GMT+08:00 wildsky <notifications@github.com>:

> Btw，我增加 android 的按鈕後，要順便調他的位置再一起送 PR 嗎？ (issue #94
> <https://github.com/moztw/www.moztw.org/issues/94> 下面提到的"下方壓字問題")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/134#issuecomment-70473199>.
>



-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by wi1d5ky** [comment]
有送 PR 囉！ （一直忘了來說一聲…
https://github.com/moztw/www.moztw.org/pull/136

**Comment by irvin** [comment]
你有沒有覺得這一頁還有任何問題？
可以上線了嗎

wildsky <notifications@github.com> 於 2015年1月22日 星期四寫道：

> 有送 PR 囉！ （一直忘了來說一聲…
> #136 <https://github.com/moztw/www.moztw.org/pull/136>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/134#issuecomment-70973745>.
>


-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by wi1d5ky** [comment]
按鈕都正常了！ 不過我發現另一個 bug，等等送 PR 上來

**Comment by irvin** [comment]
我會找時間把這個頁面整個檢查過一遍，然後就換過去了
