### ISSUE TITLE
將 /firefox 的側欄連結都加入 /firefox-new 中

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#138]
/Firefox 的側欄連結中，下方連結只有部分出現在 /firefox-new 的「社群資源」內；先全部加入再依使用率取掉。

技術支援與套件下載

    外掛程式更新
    （檢查 Flash、多媒體播放支援）
    取得套件及佈景主題
    Mozilla 技術支援中心

中文社群資源

    Firefox 中文討論區
    Youtube Firefox 影片頻道
    社群嚴選：擴充套件 Top 15
    某瀏覽器功能，Firefox 有沒有？
    新增中文搜尋引擎

推廣 Firefox

    取得 Blog 推廣貼紙 *
    臉書貼紙推廣 Firefox

* 連結至 Mozilla 網站

**Comment by wi1d5ky** [comment]
藍色字部份是原本就有的超連結，附上更改後的樣子
電腦版面基本上沒問題，只要再把連結加上去就沒事了
但手機板的 margin-left 要調一下，不然太浪費空間了
@Irvin 有沒有其他建議呢？

![2015-01-25 13 13 45](https://cloud.githubusercontent.com/assets/6042803/5890412/20594356-a494-11e4-81f7-f87affc211eb.png)
![2015-01-25 13 14 21](https://cloud.githubusercontent.com/assets/6042803/5890413/20822a32-a494-11e4-8bb5-f879feac2626.png)

**Comment by wi1d5ky** [comment]
確認一下，「中文討論區」在舊網站原本是放在「技術支援」的標題下，這邊要移到「中文社群資源」嗎?

**Comment by wi1d5ky** [comment]
PR https://github.com/moztw/www.moztw.org/pull/140

**Comment by irvin** [comment]
目標是先把 firefox-new 換上去，所以先通通放進去再說，可以再根據點擊率去調整
