### ISSUE TITLE
sandstone 首頁的下載按鈕修正

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#141]
現在 http://moztw.org/index2.shtml 的下載按鈕，好像沒辦法針對平台自動更新；需要把 /firefox-new 的下載按鈕搬過來

**Comment by irvin** [comment]
@wi1d5ky 接下來能幫忙修這個嗎？直接把你在 /firefox-new 那邊的按鈕整個搬過來看看

**Comment by wi1d5ky** [comment]
好！

**Comment by wi1d5ky** [comment]
功能可以用，但是手機版面就有點悽慘XD
![2015-01-25 14 27 15](https://cloud.githubusercontent.com/assets/6042803/5890609/89e2f376-a49e-11e4-9af1-5fcaae29ff8a.png)

**Comment by irvin** [comment]
我覺得可以參考現在moztw首頁的做法，直接就把按鈕藏起來換大圖指到 /mobile 去，省麻煩

**Comment by wi1d5ky** [comment]
這個也忘了給 PR … https://github.com/moztw/www.moztw.org/pull/142
