### ISSUE TITLE
在 /foxmosa 的外連連結加上 GA 事件追蹤

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#143]
這一樣的連結都沒有加上 GA 追蹤事件去追蹤外連，
參考其他頁面的設定， <a> 都要補上： 
onclick="ga('send', 'event', 'Outgoing', 'Firefox Mozilla - Channel', 'foxmosa');"
第四個參數是目的地頁面的簡述

**Comment by irvin** [comment]
@wi1d5ky 能幫忙補補？

**Comment by wi1d5ky** [comment]
好，我有時間的時候來弄

**Comment by wi1d5ky** [comment]
有送 PR 囉，可是可能還要作一些修改，麻煩 @irvin 幫我看看了
https://github.com/moztw/www.moztw.org/pull/144
