### ISSUE TITLE
/firefox 切換 sandstone

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#146]
確認 /firefox-new 都沒問題就替換過去

**Comment by wi1d5ky** [comment]
在想 footer 要不要修，它有點偏左邊了
![2015-01-31 20 56 04](https://cloud.githubusercontent.com/assets/6042803/5988114/9ff85c86-a98b-11e4-8ef2-2114fba18d16.png)

**Comment by wi1d5ky** [comment]
原來是 /sandstone/css/style.css 的 34 行，有個 margin: -20px 
(https://github.com/moztw/www.moztw.org/blob/master/sandstone/css/style.css#L34)
不過為什麼這邊會需要 -20px 呀@@?

**Comment by petercpg** [comment]
「推廣 Firefox」標題左邊的那個點點是不是該藏起來？

**Comment by wi1d5ky** [comment]
@petercpg 我當初是看原本有點點所以就沒把他拿掉

**Comment by petercpg** [comment]
我覺得在小螢幕的情況下有點醜 XD 然後上面的小標題也都沒有點點而且有 flow 這樣。如果不改也行，不算非常必要

**Comment by irvin** [comment]
點點真的有點醜，修了他吧。
Footer 參考首頁的樣式，在小螢幕上應該要置中（順便檢查用 sandstone 的其他頁，有些應該有做置中，可以統一改一下
