### ISSUE TITLE
Thunderbird 的下載按鈕

### ISSUE THREAD

**Issue by wi1d5ky** [moztw/www.moztw.org#149]
http://moztw.org/thunderbird/
我用 fedora 下載下來是 exe 檔...
不過按鈕上的字樣是 linux 沒錯
![2015-02-03 00 15 16](https://cloud.githubusercontent.com/assets/6042803/6003856/d3df306a-ab39-11e4-870c-59a90aa48c75.png)

**Comment by irvin** [comment]
wildsky 幫忙再檢查看看現在有沒有恢復正常了？

**Comment by wi1d5ky** [comment]
正常囉！
![2015-03-04 18 53 11](https://cloud.githubusercontent.com/assets/6042803/6482330/be7aeb6a-c29f-11e4-8c75-99a2fd6eeb76.png)

**Comment by irvin** [comment]
感謝 @VoidChen
