### ISSUE TITLE
整理 readme

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#151]
說明 
* 如何架設環境
* commit/PR 流程與原則

**Comment by wi1d5ky** [comment]
在想要不要寫到 wiki 裡面，然後 readme 給連結就好
https://github.com/moztw/www.moztw.org/wiki

**Comment by irvin** [comment]
寫在 README.md 內比較適合。
寫在 Github wiki 上，天知道那時又會遇到 Google Code 關門大吉，又需要轉移平台上 wiki 文件的事情…

**Comment by appleboy** [comment]
寫在 Readme 也比較方便看 ＸＤ

**Comment by petercpg** [comment]
https://github.com/moztw/www.moztw.org/commit/5a668f80f9a9bca12fa7118a744c04df756bad87 裡面新增了 commit 跟 PR 的流程，沒問題的話這張票能關了？
