### ISSUE TITLE
摩茲工寮頁面接上 flickr API 取得工寮群組最新照片

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#156]
說明： https://www.flickr.com/services/api/explore/flickr.groups.pools.getPhotos

JSONP 取得工寮群組最新相片：
https://api.flickr.com/services/rest/?method=flickr.groups.pools.getPhotos&api_key=2d53943173b9f1a19c06aedbb98b2ca5&group_id=2664848%40N20&format=json

**Comment by bobchao** [comment]
這我先前做完啦，看 @irvin 是不是有別的需求。
目前為了增加豐富性不是只抓最新而是會 random 一下
