### ISSUE TITLE
服務學習補上教授姓名

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#161]
http://moztw.org/events/service2013/
http://moztw.org/events/service2013q4/
在簡介最後面需要補上一段：
交大服務學習課程指導教授：林正中教授

**Comment by wi1d5ky** [comment]
這個 issue 可以 close 了～

**Comment by irvin** [comment]
Eric, 弄好了

On Sun, Mar 15, 2015 at 2:42 PM, Peter Chen <notifications@github.com>
wrote:

> Closed #161 <https://github.com/moztw/www.moztw.org/issues/161>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/161#event-254257042>.
>



-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community
