### ISSUE TITLE
Foxmosa 頁面的英文版之中有中文

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#163]
![2015-03-11 01 12 26](https://cloud.githubusercontent.com/assets/165936/6580519/19472c20-c78c-11e4-8c4b-33429a14be3e.png)
需要把 L10n 修好

**Comment by wi1d5ky** [comment]
唉呀XD 記得這是我補上去的部份:P
這個的英文要去哪裡補呢？

**Comment by petercpg** [comment]
HTML 裡面要對 element 加上 data-l10n 這個 property，然後到 /foxmosa/languages/en-US.json 裡面加上譯文即可

**Comment by wi1d5ky** [comment]
Do you wanna see more Foxmosa?
標題寫這樣會怪怪的嗎XD

**Comment by petercpg** [comment]
我會翻成 Wanna see Foxmosa in other places?

**Comment by wi1d5ky** [comment]
這個 issue 也可以 close 囉～
