### ISSUE TITLE
新版首頁小莎在說話的時候，如果字太多就會 overflow 滿到下面去

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#172]
@wi1d5ky 回報： https://github.com/moztw/www.moztw.org/issues/107#issuecomment-78502853

![36236b18-c90f-11e4-83b4-d26e39275acf](https://cloud.githubusercontent.com/assets/165936/6634669/9fd02e0c-c996-11e4-9094-25941ae8c8dc.png)

「小莎說」的高度應該動態調整，因為手機版上也會遇到一行字數變少的問題

**Comment by petercpg** [comment]
text-overflow: ellipsis 不好嗎？

**Comment by irvin** [comment]
沒什麼好處，還要讓別人點過去，還是直接換行顯示完整訊息好

Peter Chen <notifications@github.com> 於 2015年3月22日 星期日寫道：

> text-overflow: ellipsis 不好嗎？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/172#issuecomment-84433854>.
>


-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by wildskyf** [comment]
這樣小莎講別的話的時候下面的 Dom 也會亂移動？
還是你希望 min-height = heightest children dom's height？

**Comment by wildskyf** [comment]
因為怕頁面一直跳來跳去的，所以我直接計算 child 的最大高來決定那一塊的高度，大概會像這樣，
全滿的時候很ＯＫ，但字很少的時候有點空虛

![2016-12-25 20 39 10](https://cloud.githubusercontent.com/assets/6042803/21471143/402ddc8e-cae2-11e6-9b13-5951e3117e90.png)
![2016-12-25 20 38 54](https://cloud.githubusercontent.com/assets/6042803/21471144/402e467e-cae2-11e6-8792-f90e089772f4.png)


另外一種方式是不要水平置中，感覺更空虛了⋯⋯
![2016-12-25 20 42 08](https://cloud.githubusercontent.com/assets/6042803/21471155/b17cebaa-cae2-11e6-837f-994d4c8574ed.png)

**Comment by wildskyf** [comment]
目前開的 PR #509 是有 padding 的版本
