### ISSUE TITLE
thunderbird 頁面缺少ogtag

### ISSUE THREAD

**Issue by ettoolong** [moztw/www.moztw.org#176]

**Comment by wi1d5ky** [comment]
不是這一個嗎？
https://github.com/moztw/www.moztw.org/blob/master/thunderbird/inc/ogtag.shtml

**Comment by wi1d5ky** [comment]
@irvin 結果這個 issue 還是沒有 close XD

**Comment by irvin** [comment]
@wi1d5ky 我發現這邊有點問題耶， http://moztw.org/thunderbird 的 go title 是「thunderbird 版本資訊…」之類內容

**Comment by irvin** [comment]
@wildskyf ^

**Comment by wildskyf** [comment]
這邊應該要是什麼？？

**Comment by wildskyf** [comment]
噢，我懂了，他應該不能有版號？

**Comment by irvin** [comment]
cool, fixed!
