### ISSUE TITLE
把 Firefox 的下載連結獨立成 ssi var 設定檔以便 /inc/dlff  /inc/dlff-new 同時嵌入

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#186]
Firefox 的下載連結目前散落於 /inc/dlff.html /inc/dlff-new.html  /firefox/download/downloadurl.txt 三個檔案中，可參考 /inc/dltb2.shtml 的定義法、及 /thunderbird/inc/hero.shtml 的嵌入語法，把下載連結統一到一個定義檔中，以便未來更新

**Comment by irvin** [comment]
cc @bootleq

**Comment by coin3x** [comment]
可是 沒辦法 nested include 欸
這沒辦法做到吧

**Comment by irvin** [comment]
終於可以關掉了！感謝 @coin3x
