### ISSUE TITLE
/thunderbird/releases 選單順序調整 

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#194]
右側選單順序需要調整成：

    < 回 Thunderbird 首頁
    已知問題
    下載與安裝

**Comment by ddtet** [comment]
請讓我試看看這個。熟悉 git 送交程式的流程

**Comment by petercpg** [comment]
@ddtet 請做，Pull request 請發到 master branch。

**Comment by irvin** [comment]
http://moztw.org/thunderbird/releases/ 
ok 了，感謝
