### ISSUE TITLE
下載總頁上方的圖示位置需調整

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#197]
http://moztw.org/dl/ 上方的圖示位置大小不太協調，軟體名稱與下方的介紹 Slogan 也離得太遠。
![2015-03-19 01 38 59](https://cloud.githubusercontent.com/assets/165936/6715339/d65e0836-cdd8-11e4-88b1-8f3be8e328fd.png)

**Comment by eugene87222** [comment]
這樣排版OK嗎
我有先測過自己看覺得還可以

**Comment by irvin** [comment]
好一些了！

**Comment by irvin** [comment]
@eugene87222 thanks!
#540 有空也可研究一下
