### ISSUE TITLE
/thunderbird/releases/ 立即下載連結下，仍有「版本資訊」的連結

### ISSUE THREAD

**Issue by ddtet** [moztw/www.moztw.org#202]
一來是在版本資訊的頁面裡有「自己」的連結有點怪，二來是這個連結指向「releases/」，導致會連到「/thunderbird/releases/releases/」這個不存在的路徑。

也許應該拿掉這個連結，或是將它路徑改成「#」(連到自己)，不確定哪一種作法比較好。

**Comment by petercpg** [comment]
這一塊是 ssi include 進來的嗎？如果是這樣可能只能把網址連結修成 /thunderbird/releases。

Firefox 那一頁目前沒有問題，href 指到 /firefox/releases。

**Comment by wi1d5ky** [comment]
@petercpg 這個可以 close 囉

**Comment by petercpg** [comment]
沒錯，這樣修應該就 OK 了，感謝各位。
