### ISSUE TITLE
/firefox/releases 選單順序調整

### ISSUE THREAD

**Issue by petercpg** [moztw/www.moztw.org#203]
右側選單順序需要調整成：
* < 回到 Firefox 首頁
* 下載安裝
* 已知問題
* 疑難排解
* 常見問題集
* 非官方建製版

選單移除：
* 其他資源連結

作法與 #194 類似。

**Comment by wi1d5ky** [comment]
+ 回到 Firefox 首頁
+ 下載安裝
+ 已知問題
+ 疑難排解
+ 常見問題
+ 非官方建製版
+ 其他資源連結

現在的順序是這樣，好像只要把 `其他資源連結` 移掉就好？

**Comment by petercpg** [comment]
還有那個「<」 XD

基本上就是比照 #194 處理

**Comment by wi1d5ky** [comment]
了解XD 我等等來弄

**Comment by petercpg** [comment]
不放給新手弄嗎？

**Comment by wi1d5ky** [comment]
原來我不算新手了XDDD

好，還是留給其他人弄好了
剛只是想說看到能解的 issue 就先解
不過讓其他人練練 git 好了~

**Comment by hane1818** [comment]
不好意思~我第一次來，請問可以讓我試試看嗎?

**Comment by petercpg** [comment]
@hane1818 那就交給你囉，改完請開 pull request 到 `master` branch，commit message 裡面請包含這個 bug 的編號。

**Comment by hane1818** [comment]
已提出 pull request，請確認有無錯誤~謝謝

**Comment by petercpg** [comment]
@hane1818 沒問題，感謝！
