### ISSUE TITLE
/firefox/releases/ 頁面加上 OG 資訊

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#207]
參考 Mozilla 的 Release Notes 頁面的格式

    <meta property="og:type" content="website">
    <meta property="og:site_name" content="MozTW">
    <meta property="og:locale" content="zh_TW">
    <meta property="og:url" content="http://moztw.org/firefox/releases/">
    <meta property="og:image" content="https://moztw.org/images/product-firefox-v4-180.png">
    <meta property="og:title" content="Mozilla Firefox 版本資訊 (36.0.4)">
    <meta property="fb:page_id" content="109362359103769">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@moztw">
    <meta name="twitter:domain" content="moztw.org">
    <meta name="twitter:app:name:googleplay" content="Firefox">
    <meta name="twitter:app:id:googleplay" content="org.mozilla.firefox">

**Comment by irvin** [comment]
目前 fb 會自動抓取的 OG 資訊：
![2015-04-02 13 20 28](https://cloud.githubusercontent.com/assets/165936/6958187/0ddc3478-d93b-11e4-8bc7-8076fe98af88.png)

需要
* 補上 og:image 資料，指向 Firefox 圖示
* og:description 需要修改成：
      Firefox 版本資訊 [2015 年 4 月 1 日 v37.0]。此版本資訊包含了 Firefox 新鮮事、下載安裝指示、以及常見問題等訊息。我們想知道您對 Firefox 的想法，歡迎到 MozTW 的 Firefox 中文討論區與我們分享意見。 
[]內需要根據版本變動。

**Comment by kidwm** [comment]
順帶一提， `/firefox/releases/index.shtml` 不能改用 link 的方式嗎？
cc @bootleq

**Comment by bootleq** [comment]
Symbolic link 嗎？
我想是可以，但目前 index.html 和 _version_/index.html 還有差異在 `<title>`，index 會省略掉版本號。

**Comment by kidwm** [comment]
其實有個從根本解決的方法是把所有的 release note 存成原始資料再經過編譯產生 html

**Comment by wi1d5ky** [comment]
同意 @kidwm ，畢竟更新日誌都是同一個 layout，只是差在一些小地方而已，一直重複「複製→新增→修改」感覺很費工，而且還要擔心會不會有出錯或是 miss 掉的問題

**Comment by irvin** [comment]
如果只是要解決版本號的問題，那就很簡單，不要理他讓他在 index 也顯示出來就好了。
殺雞不必要用牛刀⋯⋯

wildsky <notifications@github.com> 於 2015年5月15日 星期五寫道：

> 同意 @kidwm <https://github.com/kidwm> ，畢竟更新日誌都是同一個
> layout，只是差在一些小地方而已，一直重複「複製→新增→修改」感覺很費工，而且還要擔心會不會有出錯或是 miss 掉的問題
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/207#issuecomment-102365900>
> .
>


-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by kidwm** [comment]
@wi1d5ky 你居然直接在 1e5409a2a89a579d6618a542cea9b6ec3d113281 動手改了
@bootleq 那現在 title 的差異怎辦？

我另外有個想法是用 rewrite 把 /releases/40.0/ 轉到 /releases/index.shtml?40.0

然後用 SSI 去接 `$QUERY_STRING` 變數來 include 不同的檔案，這樣也能在  index.html 和 version/index.html 做出區隔

甚至如果都用上 rewrite 了，也可以把一堆 40.0/index.shtml 變回 40.0.shtml 消除中間那層資料夾

**Comment by wi1d5ky** [comment]
我也忘記我當時怎麼會直接改了…
好像當時是看到上面 @irvin 說無所謂就直接改了吧…
太久以前弄的了

**Comment by irvin** [comment]
我是覺得沒差沒錯啊，對用戶來說沒什麼影響。

**Comment by wi1d5ky** [comment]
讓 @kidwm 說的那個獨立成一個新 issue #326
這樣這個 issue 就維持只有 `/firefox/releases/ 頁面加上 OG 資訊` 的部分了。

**Comment by irvin** [comment]
![2015-12-24 18 16 51](https://cloud.githubusercontent.com/assets/165936/11993340/938e37fa-aa6a-11e5-806f-1e6d7e18ae53.png)
圖示還沒補上
desc 最後面有多餘的「Firefox 免費下載…」

**Comment by wi1d5ky** [comment]
晚上下課後來改

Irvin <notifications@github.com> 於 2015/12/24週四 18:18 寫道：
