### ISSUE TITLE
/thunderbird/releases 加上 OG 資訊

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#208]
參考 Mozilla 的 Release Notes 頁面的格式

    <meta property="og:type" content="website">
    <meta property="og:site_name" content="MozTW">
    <meta property="og:locale" content="zh_TW">
    <meta property="og:url" content="http://moztw.org/thunderbird/releases/">
    <meta property="og:image" content="https://moztw.org/images/product-thunderbird-v3.png">
    <meta property="og:title" content="Mozilla Thunderbird 版本資訊 (31.5.0)">
    <meta property="fb:page_id" content="109362359103769">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@moztw">
    <meta name="twitter:domain" content="moztw.org">

    <meta name="twitter:app:id:googleplay" content="org.mozilla.firefox">

**Comment by wi1d5ky** [comment]
我有空的時候來弄好了

**Comment by wi1d5ky** [comment]
確認一下，是要加在/releases/就好，還是release/*都要呢？

**Comment by petercpg** [comment]
都作吧？可以改成 shtml，直接 include 大部分類似的內容。

**Comment by wi1d5ky** [comment]
shtnl 有方法可以抓該頁的特定資訊(像是 front matter 那樣的感覺)嗎?
還是大部分類似的 include ，剩下的一頁一頁補上去?

**Comment by irvin** [comment]
我早一點有在測要抓本頁網址，沒辦法正確。
這邊有 SSI 可以 include 的參數：
http://httpd.apache.org/docs/current/mod/mod_include.html
類似的用 include 包成一個 shtml，每頁不同的資訊（例如 og:url ）就另外補吧


wildsky <notifications@github.com> 於 2015年3月23日 下午4:54 寫道：

> shtnl 有方法可以抓該頁的特定資訊(像是 front matter 那樣的感覺)嗎?
> 還是大部分類似的 include ，剩下的一頁一頁補上去?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/208#issuecomment-84892330>.
>



-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by petercpg** [comment]
沒有辦法 parse 頁面內容，但可以使用 #set var 和/或 #echo var 來寫某些會變動的資料，這樣以後版本變動要改的地方就比較少。

可參考 /inc/dltb2.shtml 這個檔案。

**Comment by irvin** [comment]
主要是版號吧…不過那我想另外獨立一個 issue 連下載網址一起做。


Peter Chen <notifications@github.com> 於 2015年3月23日 下午5:30 寫道：

> 沒有辦法 parse 頁面內容，但可以使用 #set var 和/或 #echo var 來寫某些會變動的資料，這樣以後版本變動要改的地方就比較少。
>
> 可參考 /inc/dltb2.shtml 這個檔案。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/208#issuecomment-84911657>.
>



-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community
