### ISSUE TITLE
/news/ 新聞頁面需要有清楚的年份標示

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#225]
現在的新聞頁面看不出來條目的年份
![2015-04-04 17 59 41](https://cloud.githubusercontent.com/assets/165936/6992229/6628587c-daf4-11e4-8520-fceac4cbf8a3.png)

**Comment by hane1818** [comment]
請問是要在每個條目前面都加上年份嗎??

**Comment by irvin** [comment]
應該只要在年與年的交界之間標明就好，比較簡潔明暸

**Comment by hane1818** [comment]
![moznews](https://cloud.githubusercontent.com/assets/8386052/7609324/7692820e-f9a4-11e4-8acd-aa32e7b6bbc0.PNG)
那就是像這樣寫嗎?
好像往上是2011
往下是2010??

**Comment by irvin** [comment]
這樣感覺還是不太清楚，把年份當成小標題，然後每個獨立年份的項目個別包 ul？

**Comment by irvin** [comment]
越上面的新聞越新沒錯，想想有什麼更好的標示方法

**Comment by hane1818** [comment]
![moznews2](https://cloud.githubusercontent.com/assets/8386052/7610034/ff3a4220-f9ab-11e4-8a1a-5508b6d8b9bb.PNG)
如果像這樣直接在 li 前加小標呢?

**Comment by irvin** [comment]
不錯啊

**Comment by hane1818** [comment]
那我就先這樣改囉~~

**Comment by hane1818** [comment]
發現裡面還有一些日期順序錯誤，和排版亂掉的問題，我順便修一下~

**Comment by hane1818** [comment]
![moznews3](https://cloud.githubusercontent.com/assets/8386052/7626524/28e75ab8-fa3d-11e4-8f9e-a45c5acd5d21.PNG)
關於日期格式的部分，需不需要統一成x 月 x 日?
因為之後的好像都沒打日@@

**Comment by wi1d5ky** [comment]
應該是只要統一就好，我的話會想把「日」補回來
看其他人怎麼說～

**Comment by petercpg** [comment]
我其實一直覺得沒有日很奇怪，但看到首頁左下角的樣式猜想可能是以前刻意拿掉的。

就首頁不放，放到 news 歸檔之後補給他一個日吧？

**Comment by irvin** [comment]
直接用 css:after content 補一個「日」吧
Peter Chen <notifications@github.com>於 2015年5月14日 週四，下午1:53寫道：

**Comment by hane1818** [comment]
可是舊的公告有的有、有的沒有，這樣手動加會不會比較好?
最新的部分再用css補上日?

**Comment by irvin** [comment]
就看要在新的加還是把舊的拿掉，只要統一就好嘍
hane1818 <notifications@github.com>於 2015年5月14日 週四，下午2:10寫道：

**Comment by hane1818** [comment]
那把舊的拿掉好了，直接用css加好像比較方便，css的部分是要改哪個檔案呢??

**Comment by irvin** [comment]
如果這個頁面沒有獨立的 CDs 檔案，那直接新增或放在活動頁面最上面都可以
hane1818 <notifications@github.com>於 2015年5月14日 週四，下午2:17寫道：

**Comment by hane1818** [comment]
修改完了，請確認~

**Comment by irvin** [comment]
上線了，感謝！
