### ISSUE TITLE
Arrange js library: jQuery

### ISSUE THREAD

**Issue by mingtsay** [moztw/www.moztw.org#229]
Pages using this library:

v1.3.2
- [/contribute/index.shtml - Line 145](https://github.com/moztw/www.moztw.org/blob/master/contribute/index.shtml#L145)
- [/events/ie8/index.shtml - Line 219](https://github.com/moztw/www.moztw.org/blob/master/events/ie8/index.shtml#L219)
- [/events/jetpack-workshop/index.shtml - Line 114](https://github.com/moztw/www.moztw.org/blob/master/events/jetpack-workshop/index.shtml#L114)
- [/events/may2009/index.shtml - Line 328](https://github.com/moztw/www.moztw.org/blob/master/events/may2009/index.shtml#L328)

v1.5
- [/events/firefox4party/index.shtml - Line 133](https://github.com/moztw/www.moztw.org/blob/master/events/firefox4party/index.shtml#L133)
- [/events/firefox4party/landing/index.shtml - Line 83](https://github.com/moztw/www.moztw.org/blob/master/events/firefox4party/landing/index.shtml#L83)

v1.7.1
- [/sandstone/js/tabzilla.js - Line 88](https://github.com/moztw/www.moztw.org/blob/master/sandstone/js/tabzilla.js#L88)

v1.7.2
- [/about/index.shtml - Line 222](https://github.com/moztw/www.moztw.org/blob/master/about/index.shtml#L222)
- [/events/app-dev-party/index.shtml - Line 78](https://github.com/moztw/www.moztw.org/blob/master/events/app-dev-party/index.shtml#L78)
- [/events/code-rush/index.shtml - Line 114](https://github.com/moztw/www.moztw.org/blob/master/events/code-rush/index.shtml#L114)
- [/events/furp/index.shtml - Line 12](https://github.com/moztw/www.moztw.org/blob/master/events/furp/index.shtml#L12)
- [/events/icos2013-html5/index.shtml - Line 247](https://github.com/moztw/www.moztw.org/blob/master/events/icos2013-html5/index.shtml#L247)
- [/events/index.shtml - Line 11](https://github.com/moztw/www.moztw.org/blob/master/events/index.shtml#L11)
- [/events/moztw-lab/index.shtml - Line 167](https://github.com/moztw/www.moztw.org/blob/master/events/moztw-lab/index.shtml#L167)
- [/events/scp0712/index.html - Line 180](https://github.com/moztw/www.moztw.org/blob/master/events/scp0712/index.html#L180)
- [/events/sopa/index.shtml - Line 42](https://github.com/moztw/www.moztw.org/blob/master/events/sopa/index.shtml#L42)
- [/mobile/index.shtml - Line 384](https://github.com/moztw/www.moztw.org/blob/master/mobile/index.shtml#L384)
- [/thunderbird/index.shtml - Line 273](https://github.com/moztw/www.moztw.org/blob/master/thunderbird/index.shtml#L273)
- [/twoffice/index.shtml - Line 2](https://github.com/moztw/www.moztw.org/blob/master/twoffice/index.shtml#L2)

v1.8.1
- [/foxmosa/index.shtml - Line 14](https://github.com/moztw/www.moztw.org/blob/master/foxmosa/index.shtml#L14)

v1.8.3
- [/community/index.shtml - Line 10](https://github.com/moztw/www.moztw.org/blob/master/community/index.shtml#L10)
- [/firefox/tw/index.shtml - Line 420](https://github.com/moztw/www.moztw.org/blob/master/firefox/tw/index.shtml#L420)
- [/inc/new_footer.html - Line 22](https://github.com/moztw/www.moztw.org/blob/master/inc/new_footer.html#L22)
- [/index.shtml - Line 294](https://github.com/moztw/www.moztw.org/blob/master/index.shtml#L294)

--

Library in the repository:

v1.3.2
- [/contribute/js/jquery-1.3.2.min.js](https://github.com/moztw/www.moztw.org/blob/master/contribute/js/jquery-1.3.2.min.js)

v1.7.2
- [/events/app-dev-party/assets/jquery.js](https://github.com/moztw/www.moztw.org/blob/master/events/app-dev-party/assets/jquery.js)
- [/events/code-rush/assets/jquery.js](https://github.com/moztw/www.moztw.org/blob/master/events/code-rush/assets/jquery.js)
- [/events/moztw-lab/assets/jquery.js](https://github.com/moztw/www.moztw.org/blob/master/events/moztw-lab/assets/jquery.js)
- [/events/scp0712/assets/jquery.js](https://github.com/moztw/www.moztw.org/blob/master/events/scp0712/assets/jquery.js)
- [/events/sopa/assets/jquery.js](https://github.com/moztw/www.moztw.org/blob/master/events/sopa/assets/jquery.js)
- [/js/library/jquery.js](https://github.com/moztw/www.moztw.org/blob/master/js/library/jquery.js)

v1.8.1
- [/foxmosa/js/jquery.min.js](https://github.com/moztw/www.moztw.org/blob/master/foxmosa/js/jquery.min.js)

**Comment by petercpg** [comment]
@alexsh 你能確定一下這邊列的 library 都換完了嗎？

**Comment by alexsh** [comment]
基本上應該是換完了，上面這個PR是查了之後還沒更的。

**Comment by petercpg** [comment]
ok 那我們就關掉這張票吧，感謝處理。
