### ISSUE TITLE
Add acknowledgement to footer and /about for new hosting service provider

### ISSUE THREAD

**Issue by petercpg** [moztw/www.moztw.org#237]
Per original request mail:
<pre>
As this is a free service for Open Source/Culture/Music without asking almost nothing in return,
We will be encouraged if you can list as on your project site, or mention us on your news/blog/article.
And if it's ok for you, please let us know!

We are:
* BlueT - Matthew Lien - 練喆明 <BlueT@BlueT.org>
* Ubuntu Taiwan LoCo Team <http://Ubuntu-TW.org> (Chinese: Ubuntu 臺灣在地推廣組)
* Computer and Network Center of National ChiNan Univertity <http://www.cc.ncnu.edu.tw> (Chinese: 國立暨南國際大學 計算機與網路中心)
</pre>

完整全銜我想就標在 /about 就好，網頁 footer 就寫成「Powered by BlueT / <a href="http://Ubuntu-TW.org">Ubuntu-TW</a> / <a href="http://www.cc.ncnu.edu.tw">NCNUCC</a> 」即可？

**Comment by irvin** [comment]
@BlutT 你的名號或 Ubuntu-TW 留一個怎麼樣，這樣感覺有點長，
or "Powered by BlueT (Ubuntu TW) & NCNUCC"

**Comment by BlueT** [comment]
Sorry for replying so late. 因為目前計畫沒有正式網站，先用
"Powered by [Ubuntu-TW](http://ubuntu-tw.org) / [BlueT](http://bluet.org) and [NCNU-CC](http://www.cc.ncnu.edu.tw)"
這個，
待計畫正式網站有了後，再換成計畫名稱，
這樣方便嗎？

另外如果方便的話，不知是否方便在 /about 中的這部份資訊下面加上聯絡訊息，讓其他需要 hosting 服務的人也能聯絡我 (BlueT@BlueT.org)？感謝！

**Comment by BlueT** [comment]
話說， MozTW 有興趣一起參與這個計畫嗎？ :-p

**Comment by irvin** [comment]
@BlueT /about 的 hosting 訊息要怎麼寫，你要不要寫簡單寫一段來說明？

**Comment by petercpg** [comment]
Commit pushed as above, @BlueT 請看看 http://www-stage.moztw.org/about/ 這樣有沒有問題，沒有問題的話就可以 deploy production 了。

參與計畫的問題我想我們可以拉回 mailing list 討論 :)

**Comment by petercpg** [comment]
deployed to prod. Closing this issue.

**Comment by BlueT** [comment]
:+1:
