### ISSUE TITLE
100學年度下學期服務學習成果網頁

### ISSUE THREAD

**Issue by appleboy** [moztw/www.moztw.org#25]
cc @irvin 

http://www-stage.moztw.org/events/service2013q4/

**Comment by appleboy** [comment]
@irvin 我還以為 assigned 什麼 Job 給我，原來是去年的東西 XD

**Comment by irvin** [comment]
把一些 close 掉卻沒 assigned 的 bug 都加一加XD

**Comment by irvin** [comment]
BTW，要不要順便來做做今年（去年上半）的XD
