### ISSUE TITLE
製作 2014 第二學期的服務學習頁面

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#260]
參考過去的成果彙整頁面： http://moztw.org/events/service2013/
網址放：  http://moztw.org/events/service2014-2/
成果列表在此： https://docs.google.com/spreadsheets/d/1ERq7-4r9KRzu0N1SYYkwHAwcWsQV5iFOkrP0VoioSoY/pubhtml?gid=1909253497&single=true

**Comment by RJHsiao** [comment]
@irvin 問一下...  
我沒有看到負責翻譯 amara 字幕的成員&大部分 MLinks 的文章沒有負責翻譯的成員名稱？  
還是說你到時候會把負責成員放上去？

**Comment by irvin** [comment]
奇怪，弄混了…那是 #162 上學期的清單 Orz （不過上學期也沒做）

**Comment by irvin** [comment]
https://docs.google.com/spreadsheets/d/1ERq7-4r9KRzu0N1SYYkwHAwcWsQV5iFOkrP0VoioSoY/pubhtml?gid=1909253497&single=true 這才是這學期的，大概是 copy-paste 錯了

**Comment by irvin** [comment]
文案：

103 學年度第二學期，MozTW 持續偕同 OSSACC 教育部校園自由軟體中心，共同執行服務學習專案。
經交通大學資訊工程學系林正中教授指導，共有九位學生貢獻個人時間，協助(翻譯網路開發文件、技術支援文件、Webmaker 教案、Mozilla Links 新聞與 Firefox OS 除錯等工作)(連結到下面錨點)，在此彙整所有同學的成果，感謝大家的貢獻。

歡迎各大專院校老師一同推廣，以貢獻自由軟體作為服務學習課程內容，詳情請聯繫 [OSSACC](http://ossacc.moe.edu.tw/modules/tinyd0/index.php?id=1)。

**Comment by RJHsiao** [comment]
奇怪我把commit squash 成一個了，怎麼這邊看到的還是3個...

**Comment by irvin** [comment]
events/ 下面要放上連結

**Comment by irvin** [comment]
done, thanks
