### ISSUE TITLE
建立 /firefox-new/index.html 並使用 cononical 設定指向回 /firefox

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#277]
由於先前開發中用的 /firefox-new 被搜索引擎 index 了，他目前有一定流量，
因此我們需要建立 dummy 頁，將用戶轉址回 /firefox，並透過 canonical 告知搜索引擎

**Comment by petercpg** [comment]
反正 git flow 也不推薦這樣用，不直接丟去新 branch，然後從 master/production 拿掉這個資料夾，最後給 301 redirection 嗎？

**Comment by irvin** [comment]
現在 repo 沒有這個資料夾，你要幫忙設一下 301 也行
