### ISSUE TITLE
新增 telegram 頻道連結頁面

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#300]
/chat

頁面上列出現行的 telegram 頻道跟加入連結
用戶進入本頁需要先打開 recaptcha，再顯示真正的聊天室連結以防 bot

**Comment by Sea-n** [comment]
我是覺得可以用一些比較噁心不可讀的方式產生網址，讓大部分機器人失效，讓瀏覽器用 JavaScript 解，這樣使用體驗應該也會比較好

**Comment by irvin** [comment]
先通過 recaptcha 再顯示網址，應該就能擋掉大部分機器人了
/chat 是為了好記憶，讓大家只要記得 /chat 就能連到聊天室就好；itclog 也可以放到這邊來

**Comment by irvin** [comment]
頁面上線了，進一步調整： #356 #357 #358
