### ISSUE TITLE
首頁下載框的動態偵測要提供 Linux/Windows (64-bit)

### ISSUE THREAD

**Issue by petercpg** [moztw/www.moztw.org#301]
https://www.mozilla.org/en-US/firefox/all/

官方下載頁現在會給 Windows / Linux 64bit 的 tarball 了

**Comment by coin3x** [comment]
只是顯示好看的嗎？

**Comment by petercpg** [comment]
> 只是顯示好看的嗎？

什麼意思？

**Comment by coin3x** [comment]
他不是都會導到同一個連結？真的有需要特地再顯示 64 bit 嗎？

**Comment by petercpg** [comment]
https://download.mozilla.org/?product=firefox-44.0-SSL&os=win&lang=zh-TW
https://download.mozilla.org/?product=firefox-44.0-SSL&os=win64&lang=zh-TW
https://download.mozilla.org/?product=firefox-44.0-SSL&os=linux&lang=zh-TW
https://download.mozilla.org/?product=firefox-44.0-SSL&os=linux64&lang=zh-TW

連結不一樣呀？

**Comment by coin3x** [comment]
我的錯
