### ISSUE TITLE
在手機上顯示奔跑的 Foxmosa

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#329]
#78 之後在手機上奔跑 Foxmosa 是隱藏的，可以顯示在「狐耳摩莎」的字樣下面
![2015-12-25 12 05 22](https://cloud.githubusercontent.com/assets/165936/11999712/ca459bea-aaff-11e5-94e3-f13781bfbb24.png)

**Comment by wi1d5ky** [comment]
I'll take care of it

**Comment by wi1d5ky** [comment]
變成這樣 ok 嗎？
![2015-12-26 17-03-01](https://cloud.githubusercontent.com/assets/6042803/12005802/90a9456e-abf2-11e5-8d90-0447460d80a4.png)
