### ISSUE TITLE
/firefox/ 下的 "Firefox 的特色" 改用 checkbox 的寫法

### ISSUE THREAD

**Issue by wi1d5ky** [moztw/www.moztw.org#333]
在手機上現在是用 hover 的方式來展開，所以再點一次「Firefox 的特色」並不會把它收起來，改用 checkbox 來寫就可以讓他正常使用。

麻煩 @irvin 幫忙指派給我一下～ 感謝！

**Comment by wi1d5ky** [comment]
或是這個要變成 Good New Bug 也可以XD
ref: http://www.sitepoint.com/pure-css-off-screen-navigation-menu/

**Comment by bootleq** [comment]
現在 desktop 版會看到多出一個 checkbox，應該隱藏起來比較好。

**Comment by wi1d5ky** [comment]
忘記隱藏了！！

莊喬 <notifications@github.com> 於 2015/12/30週三 13:53 寫道：

**Comment by irvin** [comment]
多設一個 cursor: pointer 上去，不然電腦上滑鼠不會有指標
