### ISSUE TITLE
The "http://whatcanidoformozilla.org" will be blocked by security policy in "/contribute"

### ISSUE THREAD

**Issue by PuHsiu** [moztw/www.moztw.org#335]
In the page `"/contribute"`, there are 3 way (tabs) for new contributor: "依興趣檢視", **"依語言選擇"**, "留下資料由專人與您連繫". 

The second one is implement via `<iframe src="http://whatcanidoformozilla.org/">`, which will be **blocked by browser security policy** since any http resource is not allowed in https page.

It may cause the content block empty.

**Comment by coin3x** [comment]
Fixed by e1389e87a0e40d4ab7e21c6be6212e55976a3fa1
