### ISSUE TITLE
更新行動版頁面的下載按鈕，加入 iOS 連結

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#336]
https://moztw.org/mobile/
這邊「測試版」按鈕改成「iOS 版」按鈕
android 測試版改成文字連結，替換原本的「多語系版」字樣

**Comment by petercpg** [comment]
反正都是正式版，「正式版」字樣可以拿掉，然後等 #306 做完再一起 deploy 這個吧，文字太奇怪了。

**Comment by irvin** [comment]
上面是說兩顆按鈕直接改成 iOS 版跟 Android 版
測試版改成文字連結
