### ISSUE TITLE
手機 foxmosa 跑地球的下方上一條陰影

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#342]
在紫色的地方上一個淡淡的向上陰影，讓地球的切斷處比較不突兀（效果就像是下方的底色蓋住了上方的地球，或地球從桌布上的洞中冒出來）

![moztw - 1](https://cloud.githubusercontent.com/assets/165936/12007537/bf8c12c0-ac43-11e5-934c-3519aa2c5761.png)

**Comment by wi1d5ky** [comment]
好像不錯，我想一下怎麼弄

**Comment by eugene87222** [comment]
這樣還可以嗎@@
感覺怪怪的

**Comment by wildskyf** [comment]
@eugene87222  建議上個截圖

**Comment by eugene87222** [comment]
![fox](https://user-images.githubusercontent.com/24380544/27465058-9c05e764-5803-11e7-9b5f-169c2a6a15b9.JPG)

**Comment by irvin** [comment]
@eugene87222 
ano... 陰影可以不用是紫色，那是示意而已XD 
試試看不同深度的黑色調調看吧～

**Comment by wildskyf** [comment]
試試看 rgba(0,0,0,0.5) 把 0.5 調成 0~1  之間你覺得看起來最好的數字ＸＤ

**Comment by eugene87222** [comment]
![fox](https://user-images.githubusercontent.com/24380544/27481924-d0af950c-5851-11e7-9814-eb459b62ff69.JPG)
這樣會太淡嗎

**Comment by irvin** [comment]
![2017-06-23 20 40 01](https://user-images.githubusercontent.com/165936/27482999-2ae480ba-5856-11e7-8b4b-8a501b307670.png)
參考看看這個方向？

**Comment by eugene87222** [comment]
![fox](https://user-images.githubusercontent.com/24380544/27483849-917f6d46-5859-11e7-98f0-08b597e7a4da.JPG)
像這樣嗎?

**Comment by irvin** [comment]
再淡一點點就 ok 了！讓他不會這麼硬

**Comment by eugene87222** [comment]
![default](https://user-images.githubusercontent.com/24380544/27485833-edf80482-5860-11e7-8484-efeebd2b46cd.JPG)
調整了~~~

**Comment by irvin** [comment]
thanks!
