### ISSUE TITLE
把其他幾個群組連結都放進 telegram 頁面

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#357]
mozillians, amara-eng, amara...

**Comment by Sea-n** [comment]
請問要放哪類的連結？最後是否會演變為另一個專案？

**Comment by irvin** [comment]
不會，純粹 moztw 相關的
# MozTW 字幕組 - https://telegram.me/joinchat/AutpyAC4ZZF7syTysmXPOg
# mozilla-video-l10n (en) - https://telegram.me/joinchat/AutpyAGi7CL74m0Zs7pPTA
# MozTW Design - https://telegram.me/joinchat/AutpyAHfYs0BX2ZfX9XwYA
# Foxfooder - https://telegram.me/joinchat/AutpyAJlAH_DT1o80qwbhQ
# Mozillians (en) - https://telegram.me/joinchat/AutpyDvFHJHnUD9OZdPtlg

暫時就這樣吧
