### ISSUE TITLE
修復 telegram 網頁的 mobile 版面

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#358]
加上適當的 meta viewport 設定，讓他在手機上打開來寬度正常

**Comment by Sea-n** [comment]
已在 #359 加入 viewport 資訊，讓 Google reCAPTCHA 自動適應手機螢幕

**Comment by irvin** [comment]
![2016-01-26 13 02 36](https://cloud.githubusercontent.com/assets/165936/12572903/17b59740-c42d-11e5-98ab-ce0b41dfa22a.png)
resolved fixed, tks.
