### ISSUE TITLE
index.php 不會預設載入

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#362]
https://moztw.org/events/fxu12rp/ 
https://www-stage.moztw.org/community/telegram/ 
需要用到 index.php，但是目前不會自動載入

**Comment by irvin** [comment]
@petercpg  我試著把 stage 的 vhost.conf 的 directlyindex 加上 index.php 但是無效

**Comment by petercpg** [comment]
我們用 mod_proxy 來接 *.php 的 request，DirectoryIndex 是 Apache 這邊的事，php 不會知道那個 / 後面是什麼。

我想比較好的做法是把 /community/telegram/index.php 改回 community/telegram.php，然後 fxu12rp 的 redirection 寫回到 .htaccess。

**Comment by irvin** [comment]
目標是要讓他只有 /telegram/ 而不要有 .php 冒出來，有其他解嗎？

**Comment by petercpg** [comment]
我可以針對這個路徑特別寫規則，但要做到 DirectoryIndex 的功能應該要換 nginx 才有可能。

https://www-stage.moztw.org/community/telegram/

**Comment by irvin** [comment]
知道之前的機器上為什麼能動嗎？
Peter Chen <notifications@github.com>於 2016年1月27日 週三，下午8:26寫道：

**Comment by irvin** [comment]
或是 forum 那邊為什麼也是吃 index.php 能動？
Irvin Chen <irvin@mail.moztw.org>於 2016年1月27日 週三，下午8:48寫道：

**Comment by petercpg** [comment]
不知道，或許是版本不同的變動，Forum 是 5.6，www 是 7.0。

**Comment by mingtsay** [comment]
Apache / nginx 應該不難替換，只是好奇問題是在 httpd 還是 php ？感覺上面講得比較像是 httpd 的問題

Peter Chen <notifications@github.com> 於 2016年1月27日週三 21:20 寫道：

> 不知道，或許是版本不同的變動，Forum 是 5.6，www 是 7.0。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/362#issuecomment-175621939>
> .
>
-- 

Best regards,
Ming Tsay.

小喵 / 蔡璨名
Contact: +886-910-203-014
Website: https://mt.rmstudio.tw
RM Studio <https://rmstudio.tw> Founder
MozTW (Mozilla 台灣社群) <http://moztw.org>
銘傳大學 <http://www.mcu.edu.tw> CSIE <http://www.csie.mcu.edu.tw> 主機負責人

**Comment by petercpg** [comment]
Apache 一直都是 2.4，也沒有理由另一個 vhost 可以這裡不行。

**Comment by Vdragon** [comment]
我也遇到這個問題，根據我對 Apache 粗淺的使用經驗 `dir/index.*` 應該要被 Web server 視為 `dir` 的傳回頁面才對

不過想必 moztw.org 的 Apache 設定應該改了不少...

**Comment by mingtsay** [comment]
<IfModule dir_module>
    DirectoryIndex index.php index.html index.htm
</IfModule>

應該是這樣吧？

而 nginx 則是：
server {
    index index.php index.html index.php;
}

Ｖ字龍(Vdragon) <notifications@github.com> 於 2016年2月1日週一 14:45 寫道：

> 我也遇到這個問題，根據我對 Apache 粗淺的使用經驗 dir/index.* 應該要被 Web server 視為 dir 的傳回頁面才對
>
> 不過想必 moztw.org 的 Apache 設定應該改了不少...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/362#issuecomment-177807522>
> .
>
-- 

Best regards,
Ming Tsay.

小喵 / 蔡璨名
Contact: +886-910-203-014
Website: https://mt.rmstudio.tw
RM Studio <https://rmstudio.tw> Founder
MozTW (Mozilla 台灣社群) <http://moztw.org>
銘傳大學 <http://www.mcu.edu.tw> CSIE <http://www.csie.mcu.edu.tw> 主機負責人

**Comment by irvin** [comment]
就是  `DirectoryIndex index.php index.html`  沒效才奇怪，問題是 index.php 無效的同時，又會自動去找 index.html

**Comment by mingtsay** [comment]
在 php 那邊也有一個預設網頁，兩邊都要設定好才行，是在 fastcgi 的參數設定的！！

Irvin <notifications@github.com> 於 2016年2月1日週一 16:56 寫道：

> 就是 DirectoryIndex index.php index.html 沒效才奇怪，問題是 index.php 無效的同時，又會自動去找
> index.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/362#issuecomment-177860746>
> .
>
-- 

Best regards,
Ming Tsay.

小喵 / 蔡璨名
Contact: +886-910-203-014
Website: https://mt.rmstudio.tw
RM Studio <https://rmstudio.tw> Founder
MozTW (Mozilla 台灣社群) <http://moztw.org>
銘傳大學 <http://www.mcu.edu.tw> CSIE <http://www.csie.mcu.edu.tw> 主機負責人

**Comment by Sea-n** [comment]
嗯...
我在 .htaccess 修改的是不是無效，要回復嗎?

**Comment by irvin** [comment]
fixed with 5d54af00bb89587745cb73da71eb7d15d856b184
