### ISSUE TITLE
檢查外部連結

### ISSUE THREAD

**Issue by Sea-n** [moztw/www.moztw.org#363]
光是 HTML a tag 就包含幾百個連結，需要有人檢查是否網域已失效、不該出現在 MozTW 、 使用 `<a href="//domain">` 但無 HTTPS 或是憑證失效

**Comment by petercpg** [comment]
應該要掃完整的 URI 而不是只列 hostname 而已？

另外掃出來的東西要人工檢查，可能因為時代的關係需要留存。

Sean <notifications@github.com> 於 2016年1月26日 下午3:27 寫道：

> 光是 HTML a tag 就包含幾百個連結，需要有人檢查是否網域已失效、不該出現在 MozTW 、 使用 但無 HTTPS 或是憑證失效
> <//domain>
> <//domain>
>
> 簡單掃描到的列表: <//domain>http://rhc.sean.idv.tw/moz-link
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/363>.
>



-- 
Peter Pin-Guang Chen (petercpg)
Chinese (Traditional) [zh-TW] Localization Project Coordinator
Mozilla Taiwan Community (MozTW) http://moztw.org

**Comment by irvin** [comment]
@Sea-n 你的列表現在 404

**Comment by Sea-n** [comment]
再找了一次，提供參考
https://gist.github.com/Sea-n/48d0c2fdc72fd518aff55348d4e6b5e5
