### ISSUE TITLE
/telegram 頁面 UX 修正

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#371]
1. 「我不是機器人」通過之後，應該自動顯示出連結（隱藏 captcha、顯示連結；或直接頁面轉向），不需要人再去點 submit 按鈕
2. 加入連結點選要跳出新視窗（否則用戶從 telegram 上一頁回來時，又會需要重新通過 captcha）

**Comment by mingtsay** [comment]
要透過 AJAX 驗證，我可以協助修改 PHP Script

Irvin <notifications@github.com> 於 2016年2月1日週一 19:22 寫道：

>
>    1. 「我不是機器人」通過之後，應該自動顯示出連結（隱藏 captcha、顯示連結；或直接頁面轉向），不需要人再去點 submit 按鈕
>    2. 加入連結點選要跳出新視窗（否則用戶從 telegram 上一頁回來時，又會需要重新通過 captcha）
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/371>.
>
-- 

Best regards,
Ming Tsay.

小喵 / 蔡璨名
Contact: +886-910-203-014
Website: https://mt.rmstudio.tw
RM Studio <https://rmstudio.tw> Founder
MozTW (Mozilla 台灣社群) <http://moztw.org>
銘傳大學 <http://www.mcu.edu.tw> CSIE <http://www.csie.mcu.edu.tw> 主機負責人

**Comment by Sea-n** [comment]
> 要透過 AJAX 驗證，我可以協助修改 PHP Script
目前已經是按 Sumbit 觸發 onclick 事件 AJAX 取的網址了，現在問題是我這幾天沒好好查如何自動送出 AJAX....

**Comment by Sea-n** [comment]
JavaScript (jQuery?) 的部分感謝 @coin3x 提供 (雖然表面上是我提交的)

**Comment by coin3x** [comment]
自動送出 AJAX 完成了

**Comment by mingtsay** [comment]
👍

Coin <notifications@github.com> 於 2016年2月9日週二 13:44 寫道：

> 自動送出 AJAX 完成了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/371#issuecomment-181719556>
> .
>
-- 

Best regards,
Ming Tsay.

小喵 / 蔡璨名
Contact: +886-910-203-014
Website: https://mt.rmstudio.tw
RM Studio <https://rmstudio.tw> Founder
MozTW (Mozilla 台灣社群) <http://moztw.org>
銘傳大學 <http://www.mcu.edu.tw> CSIE <http://www.csie.mcu.edu.tw> 主機負責人

**Comment by irvin** [comment]
👍
