### ISSUE TITLE
event 頁面的 jquery 死掉導致頁面的互動壞了

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#376]
https://moztw.org/events/
![2016-02-17 17 27 48](https://cloud.githubusercontent.com/assets/165936/13105034/d02e2cea-d59b-11e5-975f-777a21623684.png)

**Comment by Larry0220** [comment]
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

line 30 使用

**Comment by irvin** [comment]
幫忙改看看然後發個 PR?

**Comment by Larry0220** [comment]
我還不會用git，我把原來 line 30
<script>jQuery(function($) ... </script>
移到最底下，看起來是能正常運作

2016-03-23 23:50 GMT+08:00 Irvin <notifications@github.com>:

**Comment by appleboy** [comment]
@irvin @Larry0220 根據 @Larry0220 的測試，我修正了一版，本來要發 PR 的，不小心直接改了 ORZ，麻煩在測試看看。

**Comment by irvin** [comment]
@appleboy 下次 GoodNewBug 不要動手，要留給新人改啊～

**Comment by appleboy** [comment]
@irvin 啊啊 ... 好的  我手誤  抱歉了
