### ISSUE TITLE
補充 /about 中 OSSPlanet 的敘述

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#377]
目前的特別感謝內容：

> 本站主機由 Ubuntu 臺灣在地推廣組（Ubuntu-TW）、練喆明先生（BlueT）及國立暨南國際大學計算機與網路中心（NCNU-CC）聯合提供代管服務，也感謝中研院資創中心 自由軟體鑄造場（OSSF）到 2015/04 前，以及台大資訊系（NTU CSIE） 到 2004/08 前的支援。

加上 OSSPlanet 資訊成為：

> 本站主機由 [OSSPlanet](http://ossplanet.net/)（Ubuntu 臺灣在地推廣組 Ubuntu-TW、練喆明先生 BlueT 及國立暨南國際大學計算機與網路中心 NCNU-CC）提供代管服務。也感謝中研院資創中心自由軟體鑄造場（OSSF）至 2015/04 前，以及台大資訊系（NTU CSIE）至 2004/08 前的支援。

**Comment by petercpg** [comment]
先不必動，BlueT 有提過等 OSSPlanet 頁面弄好再改。

**Comment by petercpg** [comment]
http://ossplanet.net/

**Comment by BlueT** [comment]
:+1
