### ISSUE TITLE
在全站頁尾放上 GitHub Repo 連結

### ISSUE THREAD

**Issue by bobchao** [moztw/www.moztw.org#382]
鼓勵大家貢獻前當然好像應該先讓人方便了解這個網站的 Repo 在那 -- 如果可以直接指到這一頁，那就更棒了。

**Comment by toppy368** [comment]
您好，我找到了全站頁尾的檔案了，正準備要編輯，可是Repo該叫什麼名字好呢？ 超連結直接顯示"本頁的 GitHub Repo"，還是有什麼其他更推薦的名車呢？(這個社群應該GitHub Pages前就存在了吧！)

**Comment by wildskyf** [comment]
「source code」 ？「本站原始碼」？

**Comment by petercpg** [comment]
「協助改進本頁面」、「協助改善網站」

**Comment by toppy368** [comment]
我先暫訂這樣好了，這樣無論國內外都看得懂，也知道這是Github發布的形式「協助改進本網站 Source code form GitHub」

**Comment by petercpg** [comment]
1. Source code "from" GitHub? 這英文用法很怪。
2. footer 簡潔就好，程式碼在哪裡點過來就知道了，沒有必要多提 GitHub。

**Comment by irvin** [comment]
參考 mozilla.org 的標示法「Contribute to this site」，用「貢獻本網站 Source」好了，然後放在 聯絡本站的左邊

**Comment by toppy368** [comment]
恩，了解了 ! 那就用樓上的文字連結了 ! 
不過還有一個小問題，關於網址的小疑問：標題上面寫指向Repo或issues都可以，若根據我的習慣，原始碼我會直接指向Repo主頁面，有Debug需求的頁面則會指向這裡(偏向貢獻頁面了)
那這個超連結我該以原始碼的Repo主頁面 ? 還是Debug用的issues呢 ?

**Comment by Sea-n** [comment]
我覺得指向 Repo 比較適當
提 issue 的人相較下是少數，大多都是看看 Source Code 而已
就算是要發 issue 也可以先看看問題在哪，有能力的話直接 PR

**Comment by toppy368** [comment]
不然這樣好了，我的建議如下：
1. footer本意是放置作者群及著作權聲明，既然是全站連結，那還是放 Repo 連結比較符合本串的本意
2. issue 裏頭蒐集本網站可能有的BUG等，雖然沒那麼適合直接放在footer，但倒是與社群網頁的「
參與我們」 (位置 /contribute ) 比較接近，算是網頁貢獻的子項目，我覺得可以另開issue，看issue及推坑的方式，以及參與我們的貢獻頁面怎麼呈現比較好 ?

**Comment by irvin** [comment]
@toppy368 sandstone 樣式的頁尾已經上去了 > https://www-stage.moztw.org/firefox/index.shtml
首頁是另一個佈景，也需要加上去

**Comment by irvin** [comment]
@petercpg stage 上面的 rebuild cache 沒效，我手動上去跑過也一樣，有空檢查看看嗎？ https://www-stage.moztw.org/firefox/

**Comment by petercpg** [comment]
@irvin 我沒去追到最終的問題在哪裡，但總之在 repo 裡面 git stash 清掉 *.html 之後重新產生 cache 就好了。

**Comment by irvin** [comment]
這一個 issue 還沒解完，只加了 sandstone 的，先重開

**Comment by toppy368** [comment]
很怪的地方是，index2.shtml 最底下123行寫者
`<!--#include virtual="/sandstone/footer.shtml" -->`
但前幾天開發時去檢查index2.shtml 檔案 (有開SSI的狀態) ，無法看到頁底(直接消失看不到)
正式版首頁的footer看起來也跟我中午改的檔案不同，所以看不出是哪一個檔案 ?

**Comment by irvin** [comment]
舊版佈景用的是這一個：
https://github.com/moztw/www.moztw.org/blob/master/index.shtml#L295

**Comment by bootleq** [comment]
已經在 PR #472 解決，應該可以上線了。

**Comment by irvin** [comment]
pushed to production

**Comment by irvin** [comment]
resolved fixed, thanks!
