### ISSUE TITLE
統一 MozTW 的 Telegram 連結

### ISSUE THREAD

**Issue by Sea-n** [moztw/www.moztw.org#391]
於搜尋引擎 (例如 [Google](http://lmgtfy.com/?q=MozTW+Telegram)) 上會找到許多原 Telegram 的 join link ，需要網頁所有人改成 moztw.org/telegram

例如：
* https://old.etherpad-mozilla.org/moztw-meta-pages
* https://m.facebook.com/MozTW/posts/966832856690044

**Comment by irvin** [comment]
第二個我把網址改了，但是他的附件無法更新
第一個是舊的 mopad，那邊沒辦法改

**Comment by irvin** [comment]
有看到其他網址再 re open~
