### ISSUE TITLE
調整首頁下載 Firefox 的 win/linux 的 64bit 選項

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#406]
更新，目前結論是首頁要：

1. 先隱藏 windows 64bit 版
2. 64bit linux 上提供 linux 64bit 版，隱藏 linux 32bit 版連結

這樣同時就只會顯示三個版本，跟原本一樣，比較簡單

--最好能直接在 32bit 的 OS 上隱藏 64bit 的項目，不然拉的太長了，用戶也會不知道該點哪一個--

**Comment by irvin** [comment]
方案有兩個：
1. 64bit 的機器上，只顯示 64bit 的下載，32bit 的機器上只顯示 32bit 的下載（但是現在 64bit 有全面推動了嗎？）
2. 64bit 的機器上，顯示 64bit 跟 32bit 的下載，隱藏非該 OS 的選項（但是一般用戶還是不知道怎麼選）

**Comment by irvin** [comment]
現在用 64bit win 跟 linux 去 mozilla.org/en-US 下載 firefox，會直接給 64bit 版了嗎？如果官方會自動給 win64，那我們就可以照著作不管了。

**Comment by medicalwei** [comment]
When getting the download link from mozilla.org/en-US, it is 64-bit Firefox link for amd64, and 32-bit Firefox link for i386.
In Windows, it is the link to a downloader, and I can assume it is x86 version judged by its installation location.

![parallels picture](https://cloud.githubusercontent.com/assets/74481/14279610/bcb3c6b2-fb60-11e5-9b45-8b8a4086842d.png)

**Comment by veloci85** [comment]
同上，win10 x64在 mozilla.org/en-US 下載 firefox 會得到 Stub 線上安裝檔 (e.g. Firefox Setup Stub 45.0.1)
實際安裝確認，以該檔案安裝的 Firefox 為32-bit 版本無誤。
![01](https://cloud.githubusercontent.com/assets/1804185/14282452/68417d04-fb79-11e5-9900-c3b4db7cc653.png)

**Comment by irvin** [comment]
結論是：

1. 先隱藏 windows 64bit 版
2. 64bit linux 上提供 linux 64bit 版，隱藏 linux 32bit 版連結

這樣同時就只會顯示三個版本，跟原本一樣，比較簡單

**Comment by mingtsay** [comment]
👍

Irvin <notifications@github.com> 於 2016年4月8日週五 21:24 寫道：

> 結論是：
>
>    1. 先隱藏 windows 64bit 版
>    2. 64bit linux 上提供 linux 64bit 版，隱藏 linux 32bit 版連結
>
> 這樣同時就只會顯示三個版本，跟原本一樣，比較簡單
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/406#issuecomment-207431334>
>
-- 

Best regards,
Ming Tsay.

小喵 / 蔡璨名
Contact: +886-910-203-014
Website: https://mt.rmstudio.tw
RM Studio <https://rmstudio.tw> Founder
MozTW (Mozilla 台灣社群) <http://moztw.org>
銘傳大學 <http://www.mcu.edu.tw> CSIE <http://www.csie.mcu.edu.tw> 主機負責人

**Comment by irvin** [comment]
感謝上面 patch，另外在非 linux 64bit 的環境下，也把 Linux 64bit 隱藏起來好嗎？

**Comment by irvin** [comment]
Thanks!
