### ISSUE TITLE
community/telegram 支援 public group 的 join link

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#416]
有些 super group 會有公開的加入連結，eg.,  https://telegram.me/mozvideol10n
目前的設計無法支援這一類的連結

**Comment by Sea-n** [comment]
現在是假如是 `https://telegram.me/joinchat/A8eCpTuH8Omg` 就傳 `A8eCpTuH8Omg`

為了支援 Supergroup Link 就用 `@Mozillians` 的格式傳給瀏覽器，再用 JavaScript 判斷開頭為 `@` 時輸出成 `https://telegram.me/Mozillians` 應該可行吧？
