### ISSUE TITLE
[space] 工寮借用申請表單

### ISSUE THREAD

**Issue by petercpg** [moztw/www.moztw.org#425]
常常有人借用工寮都還需要我們再次發信確認活動內容/性質/授權/etc.
可以串接 typeform/google doc 或任何之類的服務讓人填表後回覆。

**Comment by petercpg** [comment]
I think we can follow this issue: https://github.com/mozilla/community-spaces/issues/3

**Comment by bobchao** [comment]
這張票要定義表單而已，還是要實作到什麼程度？ 我可以先用 Google form 做一個，如果是這個程度可以先 assign 給我

**Comment by petercpg** [comment]
這一張 bug 可以先當作 meta bug，另外再開一張來做 Google Form 表單

**Comment by irvin** [comment]
有 https://docs.google.com/forms/d/1eeG8Raw1kxa9zoldTmnSBsdxfZj1urDyX2Gp7WoTyRk/viewform
應該是可關了
