### ISSUE TITLE
[space] 把老 etherpad 上面的文件整理到其他的協作平台

### ISSUE THREAD

**Issue by petercpg** [moztw/www.moztw.org#426]
例如說移到 hackpad

包含但不限於 Space 頁面底下的「營運中心」、「使用規範」等連結。

**Comment by bobchao** [comment]
啊這我一陣子前大致做完了耶，沒注意到這邊有 issue，檢視一下？ 
http://folder.moztw.org/moztw-space

**Comment by bobchao** [comment]
先給大光檢視一下看哪裡要加強

**Comment by irvin** [comment]
你是全都搬了還是只有搬工寮相關的？

**Comment by irvin** [comment]
喔我看到標題有 [space] 了

**Comment by petercpg** [comment]
看起來沒問題了，不過有些死連結跟過時資訊看要不要修掉?不用的話可以直接關掉這個 bug 了

- badges 都死掉了
- 週邊餐點商家資訊還是 CLBC 那邊的

**Comment by bobchao** [comment]
badge 拿掉了，周邊商家那邊多開了一頁大家有興趣再加光華這邊的，關票
