### ISSUE TITLE
firefox2party 頁面校園巡迴講座的 title 跟活動的總索引按鈕並在一起了

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#442]
https://www-stage.moztw.org/events/firefox2party/
「校園巡迴推廣講座
想多認識 Firefox 2？十一月中起，參加 Firefox 校園巡迴推廣講座，再造網路新體驗！我們將介紹 Firefox 2 的特異功能，帶您了解在全球造成「火狐熱」的原因。」
他的正確位置應該是在三顆按鈕之下

**Comment by irvin** [comment]
@wildskyf

**Comment by wildskyf** [comment]
像這樣嗎？
![2016-06-28 22-57-56](https://cloud.githubusercontent.com/assets/6042803/16420402/c68f1f0a-3d83-11e6-8fb3-c44014bf0a5d.png)

**Comment by irvin** [comment]
yes, 有點怪怪的不過總是比原本好
上面那三格讓他置中好了

**Comment by wildskyf** [comment]
或是我試試看能不能讓他變寬，左右對齊？

**Comment by irvin** [comment]
good
