### ISSUE TITLE
將 telegram 頁面加入各頻道的介紹

### ISSUE THREAD

**Issue by shangkuanlc** [moztw/www.moztw.org#447]
http://moztw.org/community/telegram/ ，請更新為：
-  MozTW -- 通用頻道。歡迎新手從此開始參與，各式各樣的專案、想法都可以在此提出。
-  MozTW 字幕組 --影片字幕子頻道。關於 Mozilla 相關的影片字幕的翻譯與時間軸討論
-  MozTW Design --設計子頻道。關於 Mozilla 相關的美工、圖案的設計討論。
-  MozTW 手工藝群組 -- 手工藝子頻道。例如拼豆、布偶等，主要以與 mozilla 相關周邊為主，好玩吸引人，軟性的設計討論。
-  Foxfooders (zh) -- Foxfooder專案台灣子頻道（專案已停止）。另有B2G頻道。
-  MozTW dev/add-on -- 開發者及套件子頻道。
-  MozTW@高雄 -- 高雄摩茲事務子頻道。
-  Mozillians -- 國際摩茲人子頻道，以英文為主要溝通語言。
-  mozilla-videol10n -- 摩茲影片國際在地化頻道，以英文為主要溝通語言。
-  Foxmosa Sticker -- 加入狐爾摩莎（小莎）的 telegram 貼紙之連結。

http://moztw.org/community/telegram/en ，請更新為：
-  MozTW-- General channel. Mainly uses Chinese, but most people understands English.
-  Mozillians-- Sub channel for international Mozillians. 
-  mozilla-videol10n-- Sub channel for localization of Mozilla related videos.
-  Foxmosa Sticker-- Download foxmosa stickers in telegram.

**Comment by irvin** [comment]
![2016-08-02 16 28 14](https://cloud.githubusercontent.com/assets/165936/17322034/22643094-58ce-11e6-9229-ce67cc7d019c.png)
把各頻道的敘述加到頻道名稱下方

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz

**Comment by irvin** [comment]
fixed on https://github.com/moztw/www.moztw.org/pull/451
thanks @hanbz
