### ISSUE TITLE
首頁快速連結加上 /foxmosa

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#458]

**Comment by toppy368** [comment]
已增加pull resquests，編號#463

**Comment by toppy368** [comment]
阿 ! 改好之後發現連結沒增加，原本以為是快取問題，結果今天用別台電腦看一樣沒有，後來才知道我只改index2.shtml，沒改到index.html，我有空再修改+測試好了

**Comment by toppy368** [comment]
已更新，Pull requests 編號為 #467

**Comment by toppy368** [comment]
先前的Pull requests #463 忘了張貼上來，現在首頁已顯示出此連結

**Comment by irvin** [comment]
cool
