### ISSUE TITLE
shell script 的 rebuild cache 機制好像壞了

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#471]
https://www-stage.moztw.org/firefox/index.shtml
https://www-stage.moztw.org/firefox/index.html
shtml 的 footer 有 #382 的內容，但是 html 沒有，rebuild cache 也不會像過去自動砍掉 html 重生

**Comment by irvin** [comment]
https://github.com/moztw/www.moztw.org/issues/382#issuecomment-254050020

**Comment by petercpg** [comment]
這張票應該開在 https://github.com/moztw/base 才對。你看到有新進來的內容是我正好砍掉舊的 index.html 在找問題。

初步看起來是不知道為什麼處理從 shtml 產生 html 檔案的 https://github.com/moztw/base/blob/master/autoupdate/cacheshtml.sh 這隻檔按認為 shtml 檔沒有變動不需要更新，也無法強制更新。

**Comment by irvin** [comment]
> （不過話說回來為什麼我們不直接讓 index.shtml 當成 defaultindex 就好？）
讓機器不用每次組靜態頁面，所以就是 cache

**Comment by kidwm** [comment]
這應該有方法可以讓 Apache 設定 ssi cache 吧

**Comment by irvin** [comment]
https://httpd.apache.org/docs/2.2/caching.html 或許是可以，看誰能研究一下

**Comment by irvin** [comment]
force rebuild 在這邊修好了，https://github.com/moztw/base/commit/0e28b3407f0abe1794b99fa78407c5e72508e201
但是一般的比對檔案日期的更新模式，應該還是不會動

**Comment by irvin** [comment]
https://github.com/moztw/www.moztw.org/settings/hooks/1280914#delivery-response 看最新的 master 的 github hook 好像是好的，然後 rebuild 也好了，先 close
