### ISSUE TITLE
製作 2016 上半年「台師大資訊社服務學習成果頁面」

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#480]
參考過去的成果彙整頁面： http://moztw.org/events/service2014-2/
網址放： http://moztw.org/events/service2016-1/
成果列表在此： 

暱稱 / ID	項目
Yuan
Amara 字幕聽打 / 翻譯
https://www.amara.org/en/profiles/profile/534341/

1. [English subtitle] Contributor Story - Orabile Mudongo  http://amara.org/en/videos/PBtBn60cvltb/en/1282127/
2. [English subtitle] Contributor Story - Candy Tricia Khohliwe   https://www.amara.org/en/videos/cmIM8kJ46weo/en/1282750/
3. [English subtitle] Contributor Story - San Emanuel James   http://www.amara.org/kn/videos/lQfwWdV1NvQY/zh-tw/1285563/
4. [English subtitle] Contributor Story - Alifa Ganiji   https://www.amara.org/en/videos/feY1kanbs4fM/en/1282803/
5. [English subtitle] Inside Mozilla, the Apple & FBI Encryption Case  https://www.amara.org/en/videos/r4knaGo4OZCi/en/1270069/
6. [English subtitle] Unboxing the New Firefox   https://www.amara.org/en/videos/Kxal4fctrPxa/info/unboxing-the-new-firefox/
7. [English subtitle] Sh!t mozillians say    https://www.amara.org/en/videos/XDvDyhpThz3A/zh-tw/1375302/
8. [Eng]  Introduction to Let's Encrypt  https://www.amara.org/en/videos/jgYwLToRQvIo/en/1295272/
8. [Chinese subtitle] Firefox Test Pilot: Suit up and take experimental features for a test flight   https://www.amara.org/en/videos/67RK7mJwVZ5L/zh-tw/1344272/
9. [Chinese subtitle] Stand Up for Strong Encryption   https://www.amara.org/en/videos/4v2O4bfmiw4y/zh-tw/1326667/
10. [Chinese subtitle] Encryption, Journalism, and Free Expression   https://www.amara.org/en/videos/OlXdxgCjKDrz/zh-tw/1320066/"

Ming
1. 修復 Servo 專案之 issue #10884 (https://github.com/servo/servo/issues/10884)，並提交 PR (https://github.com/servo/servo/pull/10892)
2. 修復 Saltfs 專案之 issue #343 (https://github.com/servo/saltfs/issues/343），並提交 PR (https://github.com/servo/saltfs/pull/345)

蒼天炎劍	
1. 翻譯 : Firefox 41 will use less memory when running AdBlock Plus  http://mozlinks.moztw.org/2017/01/adblock-plus-firefox.html

**Comment by irvin** [comment]
成果列表整理好了，有興趣的人可開工製作頁面了

**Comment by irvin** [comment]
@smid191394 可以幫忙也把頁面放到 moztw.org/events 去嗎？ 參照 2014 跟 2016 中間那個連結放就行了，位置在 2015/12 上面那一排第一個

**Comment by irvin** [comment]
1. 活動頁標題更正為
> 104 學年度第二學期台師大資訊社服務學習成果總覽
2. 敘述請幫忙修改
> 經交通大學資訊工程學系林正中教授指導，共有三位學生貢獻個人時間
改成
> 共有三位台師大資訊社學生貢獻個人時間

**Comment by irvin** [comment]
@wildskyf 能幫忙找一下你們學校 Logo 或社徽嗎？

**Comment by wildskyf** [comment]
這個行嗎？

https://github.com/NTNUCIC


2017年6月8日 上午1:23，"Irvin" <notifications@github.com>寫道：

**Comment by irvin** [comment]
@wildskyf 需要 Logo 圖片啦

**Comment by scott987** [comment]
社徽：[](https://github.com/NTNUCIC/NTNUCIC.github.io/blob/master/assets/images/icon.svg)

**Comment by irvin** [comment]
merged. thanks.

**Comment by irvin** [comment]
@scott987 這樣擺起來好看嗎，你們自個調調看？

<img width="1016" alt="2017-06-25 20 56 52" src="https://user-images.githubusercontent.com/165936/27516250-de88bd82-59e8-11e7-8bd5-46514a253a33.png">

**Comment by scott987** [comment]
我覺得沒問題!
