### ISSUE TITLE
年底募款把首頁指向 /donate

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#491]
差點忘了有這一頁，先前曾經推過，今年要記得推

**Comment by toppy368** [comment]
請問是這一頁嗎 ? 
https://donate.mozilla.org/zh-TW/?locale=en&utm_campaign=EOY2016

**Comment by irvin** [comment]
https://donate.mozilla.org/zh-TW/?utm_campaign=EOY2016

**Comment by irvin** [comment]
居然 duplicate #116
