### ISSUE TITLE
首頁有部分 CSS 被註解起來的用意？

### ISSUE THREAD

**Issue by wildskyf** [moztw/www.moztw.org#502]
https://github.com/moztw/www.moztw.org/blob/master/index.shtml#L8-L181

如果要不用的話應該要直接刪掉？（畢竟有 VSC 呀）

**Comment by petercpg** [comment]
那個不是註解喔，CSS 註解是 /* */。我猜是某個古早時代為了避免瀏覽器看不懂 CSS 而讓他 fallback 成註解的 dirty hack... 你把整組 style 拆掉就會發現版面爛了 XD

倒是第 8 行跟第 181 行的  可以拿掉。

**Comment by petercpg** [comment]
blame 一下 @irvin  XD

**Comment by irvin** [comment]
這是本頁的樣式沒錯
