### ISSUE TITLE
替換網站上的舊版 Firefox 圖示

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#516]
例如下面這三頁的 Firefox 圖示也太舊了吧⋯⋯
http://moztw.org/firefox/download/latest-osx.html
http://moztw.org/firefox/download/latest-win.html
http://moztw.org/firefox/download/latest-linux.html
要另外找找還有哪些地方用到舊圖示。

**Comment by irvin** [comment]
@eugene87222 可以幫忙查查看還有哪些頁面有用到舊圖示嗎？

**Comment by eugene87222** [comment]
https://moztw.org/  手機螢幕上是舊icon
https://moztw.org/mobile/  版本資訊那邊
目前找到這兩個地方

**Comment by irvin** [comment]
太好惹，如果還有發現再重開 issue 吧！
