### ISSUE TITLE
手機版 twoffice 破版

### ISSUE THREAD

**Issue by wildskyf** [moztw/www.moztw.org#525]
見附圖
![tmp_21767-screenshot_20170402-1950341302857950](https://cloud.githubusercontent.com/assets/6042803/24586930/b1419520-17de-11e7-92d9-0fade78d71a0.png)

**Comment by Rplus** [comment]
幫補 link:
http://moztw.org/twoffice/

**Comment by wildskyf** [comment]
R+ 貼心！

**Comment by Rplus** [comment]
上下兩塊

https://github.com/moztw/www.moztw.org/blob/840097ec22b80dac81a04b510b0ada3b1bed041b/twoffice/twoffice.css#L43
上面那塊為了背景留的空白加上的 `width: 610px`
懶得調可以直接改成 `max-width: 610px`


https://github.com/moztw/www.moztw.org/blob/840097e/twoffice/index.shtml#L35
主要把這個 `sw` 寬度要改成 `auto` 就好了
不過上層 CSS 的 media query 也是要處理一下才是
有個 float 會破版

104 的資料直接用 `output()` 會有很多不必要的 code
有時間可以簡單地用 `b.jobdata.data` 生

ref: http://www.104.com.tw/i/api_doc/jobsearch/qjob.cfm?sample=0&kws=java&incs=1&cols=J,JOB,NAME

**Comment by irvin** [comment]
目前下面的內容不會破版了！
但是從 width > 500 開始到 < 960 時 RWD 是無效的。
