### ISSUE TITLE
在 node 下 download 不會 work 

### ISSUE THREAD

**Issue by wildskyf** [moztw/www.moztw.org#547]
cc. @kidwm

**Comment by kidwm** [comment]
這只能讓你測試版面，是怎樣不 work?

**Comment by wildskyf** [comment]
原來只能版面，我還以為可以取代阿帕契，在那邊跟 Irvin 推薦XD

2017年6月14日 下午1:30，"Chen-Heng Chang" <notifications@github.com>寫道：

**Comment by wildskyf** [comment]
那就關掉了
