### ISSUE TITLE
/space 頁面下方的 keyholder avatar 失效

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#549]
直連到 mozillians 的都叉燒包了，需要抓檔案下來放自己這邊

<img width="1087" alt="2017-06-25 20 40 00" src="https://user-images.githubusercontent.com/165936/27516162-d4880f92-59e6-11e7-93aa-37ef0c7807b3.png">

**Comment by iigmir** [comment]
問題似乎可以透過把 `<img>` 的 `src` 屬性由 `//mozillians.org/media` 取代為 `//media.mozillians.org` 解決。不過問下，要修改網頁都是直接從 [index.shtml](https://github.com/moztw/www.moztw.org/blob/master/space/index.shtml) 手動改嗎？
![screenshot from 2017-07-06 18-40-05](https://user-images.githubusercontent.com/11061770/27907584-d026190c-627a-11e7-9641-fb63038f090b.png)

**Comment by irvin** [comment]
@iigmir 對對，請直接改 index.shtml 就可

**Comment by irvin** [comment]
因為 Mozillians 最近正在轉雲端機器，看來他們把圖片上CDN 了

**Comment by irvin** [comment]
fixed, thanks.
