### ISSUE TITLE
onboarding message 排版問題

### ISSUE THREAD

**Issue by gasolin** [moztw/www.moztw.org#559]
Nightly 上的中文 onboarding message 看起來多了個句點，因為那個句點就變三行了

![Imgur](http://i.imgur.com/mxwsBpb.png)

用 inspector 把句點移掉看起來就變正常

**Comment by bobchao** [comment]
有句點是正確的…可能看看要不要為了排版修一下句子，但可以的話應保留句點才是？

**Comment by petercpg** [comment]
感謝回報，不過這個問題跟 www.moztw.org 的 repo 好像沒有關係：
1. 原文是 "New to %S? Let’s get started."，有句點是對的。
2. 我先改成「新安裝 %S 嗎？一起開始使用吧。」，要開新 profile 才會出現實在太難測....
