### ISSUE TITLE
請官方為Focus追加功能

### ISSUE THREAD

**Issue by edenftp** [moztw/www.moztw.org#591]
1.請增加自動更新升級軟件版本功能,其他版本都有就唯讀他沒有!
2.請增加禁止網頁自動播放影音功能,參考如下:
https://www.ettoday.net/news/20170918/1013302.htm

**Comment by wildskyf** [comment]
Hi @edenftp 

感謝你對 Firefox Focus 提供寶貴的意見，
但這裡是給 Mozilla 台灣社群管理 <https://moztw.org> 網站的開發/維護的相關訊息，
不是讓 Firefox Focus 使用者提需求的地方，建議你可以前往 [Firefox Focus](https://support.mozilla.org/zh-TW/questions/focus-firefox) 提供你的意見哦～

**Comment by irvin** [comment]
請到這邊的 focus-ios 與 focus-android 的 issue 去提供意見回饋
https://github.com/mozilla-mobile
