### ISSUE TITLE
把工寮 CO2 數值嵌到網頁上

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#606]
https://thingspeak.com/channels/631210/widgets/21165
直接 iframe embed 到 /space 頁面上下面去，可參考之前同頁面上 pm2.5 的位置

**Comment by pan93412** [comment]
打算接手。

**Comment by pan93412** [comment]
https://github.com/moztw/www.moztw.org/pull/607

Done.

**Comment by irvin** [comment]
thanks
