### ISSUE TITLE
moztw.org/tg 似乎壞了

### ISSUE THREAD

**Issue by wildskyf** [moztw/www.moztw.org#609]
https://moztw.org/tg

<img width="1280" alt="2019-01-06 14 17 42" src="https://user-images.githubusercontent.com/6042803/50732864-dc0f6b80-11bd-11e9-80c1-b7fed169db52.png">

**Comment by irvin** [comment]
看來是因為這幾天主機不穩，我們看到的頁面是 transparent proxy 出的，當選完 captcha 後，需要主機上的 php 反應時就卡住了

**Comment by irvin** [comment]
主機恢復，php 回來就恢復了
