### ISSUE TITLE
移除 "參與我們"頁面的 "推廣 Mozilla"→"Firefox 夥伴計畫" 連結

### ISSUE THREAD

**Issue by chyuaner** [moztw/www.moztw.org#637]
"參與我們"頁面的 "推廣 Mozilla"→"Firefox 夥伴計畫" 連結已經失效囉

**Comment by irvin** [comment]
那個專案死掉了，請直接砍掉

**Comment by irvin** [comment]
fixed by https://github.com/moztw/www.moztw.org/pull/649
