### ISSUE TITLE
修正 Firefox 新版頁面的 Responsive

### ISSUE THREAD

**Issue by irvin** [moztw/www.moztw.org#94]
http://moztw.org/firefox-new/
在套用 Sandstone 樣式後，Responsive 有點故障

**Comment by wi1d5ky** [comment]
這頁的 RWD 我來修修看

**Comment by wi1d5ky** [comment]
https://github.com/moztw/www.moztw.org/pull/130 修成這樣
![screenshot](https://cloud.githubusercontent.com/assets/6042803/5788823/11a16f3a-9e88-11e4-8cde-082cda0ea123.PNG)
![screenshot2](https://cloud.githubusercontent.com/assets/6042803/5788831/be477f18-9e88-11e4-86ee-93ea4a95867b.PNG)

**Comment by irvin** [comment]
有寬有窄的問題也可以調整嗎？

wildsky <notifications@github.com> 於 2015年1月17日 星期六寫道：

> #130 <https://github.com/moztw/www.moztw.org/pull/130> 修成這樣
> [image: screenshot]
> <https://cloud.githubusercontent.com/assets/6042803/5788823/11a16f3a-9e88-11e4-8cde-082cda0ea123.PNG>
> [image: screenshot2]
> <https://cloud.githubusercontent.com/assets/6042803/5788831/be477f18-9e88-11e4-86ee-93ea4a95867b.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moztw/www.moztw.org/issues/94#issuecomment-70365549>.
>


-- 
@ irvinfly: community liaison
moztw.org Mozilla Taiwan community

**Comment by wi1d5ky** [comment]
好，我等等修修看

**Comment by wi1d5ky** [comment]
完成!
![寬度一致了~](https://cloud.githubusercontent.com/assets/6042803/5789762/42e842f0-9eb3-11e4-91cd-d3a26c1f72db.PNG)

**Comment by irvin** [comment]
![2015-01-19 15 40 07](https://cloud.githubusercontent.com/assets/165936/5797273/b002e734-9ff1-11e4-8d63-130d454a0d18.png)
下載鈕的位置也修一下？（下方壓字）
